# Generated by Django 6.0.6 on 2026-06-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn", models.CharField(blank=True, db_index=True, max_length=20)),
                ("title", models.CharField(max_length=500)),
                ("author", models.CharField(blank=True, max_length=300)),
                ("publisher", models.CharField(blank=True, max_length=300)),
                ("published_date", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                ("cover_url", models.URLField(blank=True, max_length=1000)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("want", "Want to Read"),
                            ("reading", "Currently Reading"),
                            ("read", "Read"),
                        ],
                        default="want",
                        max_length=10,
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_finished", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date_added"],
            },
        ),
    ]
